// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqfxtszxulqnxfczpbut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxZnh0c3p4dWxxbnhmY3pwYnV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxNjcyNTUsImV4cCI6MjA1MTc0MzI1NX0.RoX51KYQHpm7XHZD4UsdgBMFedcSn7-jiQ3-K8CZ4hg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);